altdoc: 0.7.0
pandoc: 3.1.3
pkgdown: 2.1.3
pkgdown_sha: ~
last_built: 2025-11-02T19:43:04+0000
urls:
  reference: https://eddelbuettel.github.io/digest/man
  article: https://eddelbuettel.github.io/digest/vignettes
